### ISSUE TITLE
libvirt provider not available

### ISSUE THREAD

**Issue by Keysuke** [ruzickap/packer-templates#248]
Hi,

After browsing the different boxes in https://app.vagrantup.com/peru, I noticed that the recent updates do not provide the libvirt image for the boxes anymore. Only the VirtualBox one is available.

![image](https://user-images.githubusercontent.com/12009081/108079428-16bb8180-706f-11eb-90df-6aa88f1cde87.png)

Is libvirt still supported?

Best regards.

**Comment by brikendr** [comment]
> Hi,
> 
> After browsing the different boxes in https://app.vagrantup.com/peru, I noticed that the recent updates do not provide the libvirt image for the boxes anymore. Only the VirtualBox one is available.
> 
> ![image](https://user-images.githubusercontent.com/12009081/108079428-16bb8180-706f-11eb-90df-6aa88f1cde87.png)
> 
> Is libvirt still supported?
> 
> Best regards.

+1 to that. Experiencing the same issue as well.

**Comment by ruzickap** [comment]
You are right guys and I'm sorry for that.

In the past I was building the images on spare laptop, where I was able to debug issues easily. (build of all images took about 26 hours) 

Some time ago I switched to GitHub Actions which is much faster way of building boxes, but without possibility to debug :-(
Currently I can not ssh to the VM where GitHub Actions are building the images to see what is broken.

Building Windows boxes is really hard because of these issues which are randomly happening. 
If I run the same commands on my mac - everything is working fine.

Anyway - I'll try to look at it again, but I can not promise much progress. Without access to the node where the build failed it will be really hard to troubleshoot

**Comment by brikendr** [comment]
@ruzickap is it possible to roll back to the previous revision where libvirt is supported? Have you thought doing it on Travis CI instead of github actions? They have a very thorough debug log available during and after the build is complete. Maybe a good alternative?

**Comment by ruzickap** [comment]
Yeah... It's complicated. The libvirt is supported but sometimes it's not working on the GitHub MacOc machines as expected... I saw Ansible 3.0 released yesterday so I'll give it some more love and try to make it working...

I used TravisCI some time ago and as far as I remember they do not support Qemu / VirtualBox virtualization - this is supported only in GitHub MacOS instances.
-> Please correct me if I'm wrong...

I'm not sure if I can ssh to the TravisCI instance to start debugging. 
I saw this feature only in AppVeyor (https://www.appveyor.com/docs/how-to/ssh-to-build-worker/), but I'm not sure how it looks on the market now...

**Comment by Keysuke** [comment]
The libvirt images are back on Vagrant Hub. I can confirm that the Windows 2004 image (maybe 20H2 soon?) is working as before.

I am closing this issue.
Thank you.

**Comment by deargle** [comment]
https://app.vagrantup.com/peru/boxes/ubuntu-18.04-desktop-amd64 is still missing libvirt -- <3 for these images btw
