### ISSUE TITLE
add swap

### ISSUE THREAD

**Issue by pucoder** [ruzickap/packer-templates#258]
My computer has limited resources. Could you consider adding 1024 MB of virtual memory when installing the system? I really need it, thank you

**Comment by ruzickap** [comment]
Hello.

I'm sorry but I do not plan add swap into the boxes (VMs). Having swap inside VM is a bad practice and you should avoid it as much as possible.

If you really need swap, please look at this guide: https://superuser.com/questions/1058491/is-it-possible-to-create-a-swap-file-for-a-linux-guest-vm-managed-by-vagrant

I have never tried it, because I stopped using swap few years ago.

**Comment by pucoder** [comment]
OK, thank you
