### ISSUE TITLE
Ubuntu 20.04 Desktop

### ISSUE THREAD

**Issue by amitchettri** [ruzickap/packer-templates#303]
Hi, I was wondering to check if https://github.com/ruzickap/packer-templates/blob/master/http/ubuntu-desktop/preseed.cfg can be used for the Ubuntu desktop 20.04 as well?

As  with 20.04 LTS, will be completing the transition to the live installer and discontinuing the classic i.nstaller based on debian-installer.

any update would be very helpful

**Comment by ruzickap** [comment]
I believe yes. 
That should work if you use the [Legacy Ubuntu Server Installer]( http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images):

https://github.com/ruzickap/packer-templates/blob/b929eaf8eed5c4199b68c48246586e3459c7fc9c/ubuntu-desktop.json#L2

I'm not sure how it is with "regular/current" Ubuntu installer, because there were some major changes.
