### ISSUE TITLE
windows 2019 missing driver on device manager

### ISSUE THREAD

**Issue by andwiseb** [ruzickap/packer-templates#486]
Hello friends!
How can i update exclamation drivers in device manager with autounattend? I think it should read and update the E:/ driver. Virtio Ethernet Controller and PCI.

**Comment by ruzickap** [comment]
I have no idea :-(
I'm always installing the drivers to the new Windows instance.
Updating the existing instance is something more complex...

**Comment by andwiseb** [comment]
it's not that complicated because i figured out how to do it. just add the following to the autounattend file:
`<SynchronousCommand wcm:action="add">
<CommandLine>cmd.exe /c cd /d D:\ & powershell -Command "msiexec /qn /i virtio-win-gt-x64.msi"</CommandLine
<Description>Network prompt</Description>
<Order>5</Order>
<RequiresUserInput>true</RequiresUserInput>
</SynchronousCommand>`

this way there is no need to go into device manager after installation and manually update missing devices. you can add this to the repo I think

**Comment by ruzickap** [comment]
Thank you @andwiseb for your suggestion and please please accept my apologies for slow response.

I do not plan to do any other changes to the repository, because it will require testing / fixing old bugs / updating components / etc...

I updated the `README.md` with the outdated message: https://github.com/ruzickap/packer-templates/pull/524

Thank you for understanding...
