### ISSUE TITLE
Windows core Server variant

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#492]
hi there,

would be nice to have a windows core server variant build :)

I think it shouldnt be much of an issue, just a different selection during installation?

**Comment by abbbi** [comment]
i gave it a try and created a core variant for server 2022, these are my findings:

1) i removed bleachbit and ultradefrag steps from the build workflow, they failed for me on core (and i did not attempt to analyze)
2) The shutdown_command must be called via cmd.exe /c, as windows core variant seems to default to powershell, sysprep failed if not:

```
-      "shutdown_command": "A:\\sysprep.bat",
+      "shutdown_command": "cmd.exe /c A:\\sysprep.bat",
```

**Comment by ruzickap** [comment]
Thank you Michael for your suggestion and please please accept my apologies for slow response.

I do not plan to do any other changes to the repository, because it will require testing / fixing old bugs / updating components / etc...

I updated the `README.md` with the outdated message: https://github.com/ruzickap/packer-templates/pull/524

Thank you for understanding...

**Comment by abbbi** [comment]
oh, sorry to hear this, your images were always the best and easy to adopt for newer variants!
