### ISSUE TITLE
VBoxManage: error: Unknown option: --clipboard (peru/ubuntu-18.04-server-amd64)

### ISSUE THREAD

**Issue by supkoder** [ruzickap/packer-templates#57]
I just tried to "vagrant up" with "peru/ubuntu-18.04-server-amd64 v20200104.02" and got this error:

`VBoxManage: error: Unknown option: --clipboard`

- more info from Vagrant's github:
https://github.com/hashicorp/vagrant/issues/11288

- more info about VirtualBox changes from Oracle:
https://github.com/oracle/vagrant-boxes/issues/188

---

OS: Windows 10 Home

```
> vagrant --version
Vagrant 2.2.6

> VBoxManage --version
6.1.2r135662

```

I also applied this workaround to run vagrant 2.2.6 with VirtualBox 6.1.2: 
- https://github.com/oracle/vagrant-boxes/issues/178#issue-536720633

--- 

I fixed in on my machine by editing "e:\.vagrant.d\boxes\peru-VAGRANTSLASH-ubuntu-18.04-server-amd64\20200104.02\virtualbox\Vagrantfile":

```
virtualbox.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
```

**Comment by ruzickap** [comment]
Thanks for reporting it. 
I already fixed it in #54, but I forgot to rebuild the images.

The images will be automatically rebuild beginning of next month.

I'll keep this open to let you know...

**Comment by jpruiz114** [comment]
@ruzickap is there a workaround that can be done manually to fix this locally? Thanks.

**Comment by ruzickap** [comment]
I rebuilt all the images with the working `Vagrantfile` to make it easier for all.

Please try to use the latest images and let me know...

**Comment by jpruiz114** [comment]
This is failing again under Vagrant 2.2.7 and VirtualBox 6.

A customization command failed:

["modifyvm", :id, "--clipboard-mode", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing VBoxManage, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "4a38a623-f3f1-4464-a423-39d48c758a97", "--clipboard-mode", "bidirectional"]

Stderr: Oracle VM VirtualBox Command Line Management Interface Version 6.0.16
(C) 2005-2020 Oracle Corporation
All rights reserved.

Seems like we went back to the original notation?

When using --clipboard instead of the new --clipboard-mode everything works as expected with VirtualBox 6. Is this the case? Thanks.

**Comment by ruzickap** [comment]
Hello.

May I ask you to try it with VirtualBox 6.1.x (or higher) ?
See the requirements: https://github.com/ruzickap/packer-templates#requirements

Thank you...
